version: 1.1.0.{build}
image: Visual Studio 2017

platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x86" set archi=x86

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild CodeStats.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\CodeStats
    - ps: >-

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\x64\$env:CONFIGURATION\CodeStats.dll" -FileName CodeStats.dll
        }

        if ($env:PLATFORM -eq "x86" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:CONFIGURATION\CodeStats.dll" -FileName CodeStats.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            if ($env:PLATFORM -eq "x64" -or $env:PLATFORM -eq "x86") {
                $ZipFileName = "notepadpp-CodeStats_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORM).zip"
                Remove-Item bin\$env:PLATFORM\$env:CONFIGURATION\*.exp
                Remove-Item bin\$env:PLATFORM\$env:CONFIGURATION\*.lib
                7z a $ZipFileName bin\$env:PLATFORM\$env:CONFIGURATION\*
            }
        }

artifacts:
  - path: notepadpp-CodeStats_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        configuration: Release
